package com.trungtam.ui.panels.lophoc;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*; import com.trungtam.service.LopHocService; import com.trungtam.model.LopHoc; import com.trungtam.patterns.observer.KenhSuKien; import com.trungtam.util.XuatCSV;
// Panel LopHoc CRUD + tim kiem + loc nang cao + auto refresh
public class LopHocPanel extends JPanel {
    private LopHocService service=new LopHocService(); private JTable table; private DefaultTableModel model; private JTextField txtTimKiem; private JButton btnXuatCSV; private JTextField txtTuNgay; private JTextField txtDenNgay; private JTextField txtMonId; private JTextField txtGvId; private JTextField txt_monhocId; private JTextField txt_giaovienId; private JTextField txt_phong; private JTextField txt_lich; private JTextField txt_ngaybatdau; private JTextField txt_ngayketthuc;
    public LopHocPanel(){
        setLayout(new BorderLayout(10,10)); add(taoForm(), BorderLayout.NORTH); add(taoBang(), BorderLayout.CENTER); napBang();
        KenhSuKien.dangKy("lophoc.changed", (c,d)-> napBang());
    }
    private JPanel taoForm(){
        JPanel p=new JPanel(new GridBagLayout()); GridBagConstraints g=new GridBagConstraints(); g.insets=new Insets(5,5,5,5); g.fill=GridBagConstraints.HORIZONTAL; int r=0;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Tim kiem"), g); txtTimKiem=new JTextField(); g.gridx=1; p.add(txtTimKiem,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Tu ngay (yyyy-MM-dd)"), g); txtTuNgay=new JTextField(); g.gridx=1; p.add(txtTuNgay,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Den ngay (yyyy-MM-dd)"), g); txtDenNgay=new JTextField(); g.gridx=1; p.add(txtDenNgay,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("MonHoc ID"), g); txtMonId=new JTextField(); g.gridx=1; p.add(txtMonId,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("GiaoVien ID"), g); txtGvId=new JTextField(); g.gridx=1; p.add(txtGvId,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Mon hoc ID"), g); txt_monhocId=new JTextField(); g.gridx=1; p.add(txt_monhocId, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Giao vien ID"), g); txt_giaovienId=new JTextField(); g.gridx=1; p.add(txt_giaovienId, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Phong"), g); txt_phong=new JTextField(); g.gridx=1; p.add(txt_phong, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Lich"), g); txt_lich=new JTextField(); g.gridx=1; p.add(txt_lich, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Ngay bat dau (yyyy-MM-dd)"), g); txt_ngaybatdau=new JTextField(); g.gridx=1; p.add(txt_ngaybatdau, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Ngay ket thuc (yyyy-MM-dd)"), g); txt_ngayketthuc=new JTextField(); g.gridx=1; p.add(txt_ngayketthuc, g); r++;
        JPanel actions=new JPanel(); JButton bThem=new JButton("Them"), bSua=new JButton("Sua"), bXoa=new JButton("Xoa"), bTai=new JButton("Tai lai"); btnXuatCSV=new JButton("Xuat CSV");
        actions.add(bThem); actions.add(bSua); actions.add(bXoa); actions.add(bTai); actions.add(btnXuatCSV);
        g.gridx=0; g.gridy=r; g.gridwidth=2; p.add(actions,g);
        bThem.addActionListener(e->them()); bSua.addActionListener(e->sua()); bXoa.addActionListener(e->xoa()); bTai.addActionListener(e->napBang()); btnXuatCSV.addActionListener(e->xuatCSV());
        txtTimKiem.addActionListener(e->napBang()); for (javax.swing.JTextField tf : new javax.swing.JTextField[]{txtTuNgay,txtDenNgay,txtMonId,txtGvId}) if(tf!=null) tf.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){ public void insertUpdate(javax.swing.event.DocumentEvent e){ napBang(); } public void removeUpdate(javax.swing.event.DocumentEvent e){ napBang(); } public void changedUpdate(javax.swing.event.DocumentEvent e){ napBang(); }});
        txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){ public void insertUpdate(javax.swing.event.DocumentEvent e){napBang();} public void removeUpdate(javax.swing.event.DocumentEvent e){napBang();} public void changedUpdate(javax.swing.event.DocumentEvent e){napBang();} });
        return p;
    }
    private JScrollPane taoBang(){
        model=new DefaultTableModel(new Object[]{ "ID", "Mon hoc ID", "Giao vien ID", "Phong", "Lich", "Ngay bat dau (yyyy-MM-dd)", "Ngay ket thuc (yyyy-MM-dd)" },0){ public boolean isCellEditable(int r,int c){return false;} };
        table=new JTable(model); table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.getSelectionModel().addListSelectionListener(e->chon()); return new JScrollPane(table);
    }
    private void chon(){ int i=table.getSelectedRow(); if(i<0) return; int idx=1; txt_monhocId.setText(String.valueOf(model.getValueAt(i,idx++))); txt_giaovienId.setText(String.valueOf(model.getValueAt(i,idx++))); txt_phong.setText(String.valueOf(model.getValueAt(i,idx++))); txt_lich.setText(String.valueOf(model.getValueAt(i,idx++))); txt_ngaybatdau.setText(model.getValueAt(i,idx++)==null? "": model.getValueAt(i,idx-1).toString()); txt_ngayketthuc.setText(model.getValueAt(i,idx++)==null? "": model.getValueAt(i,idx-1).toString()); }
    private void xuatCSV(){ try{ javax.swing.JFileChooser ch=new javax.swing.JFileChooser(); ch.setSelectedFile(new java.io.File("export.csv")); if(ch.showSaveDialog(this)==javax.swing.JFileChooser.APPROVE_OPTION){ XuatCSV.xuatBang(table, ch.getSelectedFile()); JOptionPane.showMessageDialog(this, "Da xuat: "+ch.getSelectedFile().getAbsolutePath()); } }catch(Exception ex){ JOptionPane.showMessageDialog(this,"Loi xuat: "+ex.getMessage()); } }
    private boolean phuHopTuKhoa(String s, String q){ if(q==null||q.isEmpty()) return true; if(s==null) return false; return s.toLowerCase().contains(q.toLowerCase()); }
    private boolean kiemTraBoLoc(LopHoc o){ String q=txtTimKiem==null?"":txtTimKiem.getText().trim(); return ((phuHopTuKhoa(String.valueOf(o.getMonhocId()), q) || phuHopTuKhoa(String.valueOf(o.getGiaovienId()), q) || phuHopTuKhoa(o.getPhong(), q) || phuHopTuKhoa(o.getLich(), q)) && (( (txtMonId==null||txtMonId.getText().isEmpty()|| String.valueOf(o.getMonhocId()).contains(txtMonId.getText().trim())) && (txtGvId==null||txtGvId.getText().isEmpty()|| String.valueOf(o.getGiaovienId()).contains(txtGvId.getText().trim())) && (txtTuNgay==null||txtTuNgay.getText().isEmpty()|| (o.getNgaybatdau()!=null && !o.getNgaybatdau().isBefore(java.time.LocalDate.parse(txtTuNgay.getText().trim())))) && (txtDenNgay==null||txtDenNgay.getText().isEmpty()|| (o.getNgayketthuc()!=null && !o.getNgayketthuc().isAfter(java.time.LocalDate.parse(txtDenNgay.getText().trim())))) ))); }
    private void napBang(){ model.setRowCount(0); java.util.List<LopHoc> list=service.timTatCa(); for(LopHoc o: list){ if(kiemTraBoLoc(o)) model.addRow(new Object[]{ o.getId(), o.getMonhocId(), o.getGiaovienId(), o.getPhong(), o.getLich(), o.getNgaybatdau(), o.getNgayketthuc() }); } }
    private void them(){ try{ LopHoc o=new LopHoc(); if(!txt_monhocId.getText().trim().isEmpty()) o.setMonhocId(Integer.parseInt(txt_monhocId.getText().trim())); if(!txt_giaovienId.getText().trim().isEmpty()) o.setGiaovienId(Integer.parseInt(txt_giaovienId.getText().trim())); o.setPhong(txt_phong.getText().trim()); o.setLich(txt_lich.getText().trim()); if(!txt_ngaybatdau.getText().trim().isEmpty()) o.setNgaybatdau(java.time.LocalDate.parse(txt_ngaybatdau.getText().trim())); if(!txt_ngayketthuc.getText().trim().isEmpty()) o.setNgayketthuc(java.time.LocalDate.parse(txt_ngayketthuc.getText().trim())); service.tao(o); }catch(Exception ex){ JOptionPane.showMessageDialog(this, "Loi them: "+ex.getMessage()); } }
    private void sua(){ int i=table.getSelectedRow(); if(i<0){JOptionPane.showMessageDialog(this,"Chon dong de sua");return;} try{ LopHoc o=new LopHoc(); o.setId((Integer)model.getValueAt(i,0)); if(!txt_monhocId.getText().trim().isEmpty()) o.setMonhocId(Integer.parseInt(txt_monhocId.getText().trim())); if(!txt_giaovienId.getText().trim().isEmpty()) o.setGiaovienId(Integer.parseInt(txt_giaovienId.getText().trim())); o.setPhong(txt_phong.getText().trim()); o.setLich(txt_lich.getText().trim()); if(!txt_ngaybatdau.getText().trim().isEmpty()) o.setNgaybatdau(java.time.LocalDate.parse(txt_ngaybatdau.getText().trim())); if(!txt_ngayketthuc.getText().trim().isEmpty()) o.setNgayketthuc(java.time.LocalDate.parse(txt_ngayketthuc.getText().trim())); service.capNhat(o); }catch(Exception ex){ JOptionPane.showMessageDialog(this,"Loi sua: "+ex.getMessage()); } }
    private void xoa(){ int i=table.getSelectedRow(); if(i<0){JOptionPane.showMessageDialog(this,"Chon dong de xoa");return;} if(JOptionPane.showConfirmDialog(this,"Xoa?","Xac nhan",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){ try{ service.xoa((Integer)model.getValueAt(i,0)); }catch(Exception ex){ JOptionPane.showMessageDialog(this,"Loi xoa: "+ex.getMessage()); } } }
}

