package com.trungtam.ui.panels.hocvien;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*; import com.trungtam.service.HocVienService; import com.trungtam.model.HocVien; import com.trungtam.patterns.observer.KenhSuKien; import com.trungtam.util.XuatCSV;
// Panel HocVien CRUD + tim kiem + loc nang cao + auto refresh
public class HocVienPanel extends JPanel {
    private HocVienService service=new HocVienService(); private JTable table; private DefaultTableModel model; private JTextField txtTimKiem; private JButton btnXuatCSV; private JTextField txtTuNgaySinh; private JTextField txtDenNgaySinh; private JTextField txt_ma; private JTextField txt_hovaten; private JTextField txt_sdt; private JTextField txt_email; private JTextField txt_diachi; private JTextField txt_ngaysinh;
    public HocVienPanel(){
        setLayout(new BorderLayout(10,10)); add(taoForm(), BorderLayout.NORTH); add(taoBang(), BorderLayout.CENTER); napBang();
        KenhSuKien.dangKy("hocvien.changed", (c,d)-> napBang());
    }
    private JPanel taoForm(){
        JPanel p=new JPanel(new GridBagLayout()); GridBagConstraints g=new GridBagConstraints(); g.insets=new Insets(5,5,5,5); g.fill=GridBagConstraints.HORIZONTAL; int r=0;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Tim kiem"), g); txtTimKiem=new JTextField(); g.gridx=1; p.add(txtTimKiem,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Tu ngay sinh (yyyy-MM-dd)"), g); txtTuNgaySinh=new JTextField(); g.gridx=1; p.add(txtTuNgaySinh,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Den ngay sinh (yyyy-MM-dd)"), g); txtDenNgaySinh=new JTextField(); g.gridx=1; p.add(txtDenNgaySinh,g); r++;
        g.gridx=0; g.gridy=r; p.add(new JLabel("Ma"), g); txt_ma=new JTextField(); g.gridx=1; p.add(txt_ma, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Ho va ten"), g); txt_hovaten=new JTextField(); g.gridx=1; p.add(txt_hovaten, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("SDT"), g); txt_sdt=new JTextField(); g.gridx=1; p.add(txt_sdt, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Email"), g); txt_email=new JTextField(); g.gridx=1; p.add(txt_email, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Dia chi"), g); txt_diachi=new JTextField(); g.gridx=1; p.add(txt_diachi, g); r++; g.gridx=0; g.gridy=r; p.add(new JLabel("Ngay sinh (yyyy-MM-dd)"), g); txt_ngaysinh=new JTextField(); g.gridx=1; p.add(txt_ngaysinh, g); r++;
        JPanel actions=new JPanel(); JButton bThem=new JButton("Them"), bSua=new JButton("Sua"), bXoa=new JButton("Xoa"), bTai=new JButton("Tai lai"); btnXuatCSV=new JButton("Xuat CSV");
        actions.add(bThem); actions.add(bSua); actions.add(bXoa); actions.add(bTai); actions.add(btnXuatCSV);
        g.gridx=0; g.gridy=r; g.gridwidth=2; p.add(actions,g);
        bThem.addActionListener(e->them()); bSua.addActionListener(e->sua()); bXoa.addActionListener(e->xoa()); bTai.addActionListener(e->napBang()); btnXuatCSV.addActionListener(e->xuatCSV());
        txtTimKiem.addActionListener(e->napBang()); if(txtTuNgaySinh!=null) txtTuNgaySinh.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){ public void insertUpdate(javax.swing.event.DocumentEvent e){ napBang(); } public void removeUpdate(javax.swing.event.DocumentEvent e){ napBang(); } public void changedUpdate(javax.swing.event.DocumentEvent e){ napBang(); }});
        if(txtDenNgaySinh!=null) txtDenNgaySinh.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){ public void insertUpdate(javax.swing.event.DocumentEvent e){ napBang(); } public void removeUpdate(javax.swing.event.DocumentEvent e){ napBang(); } public void changedUpdate(javax.swing.event.DocumentEvent e){ napBang(); }});
        txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){ public void insertUpdate(javax.swing.event.DocumentEvent e){napBang();} public void removeUpdate(javax.swing.event.DocumentEvent e){napBang();} public void changedUpdate(javax.swing.event.DocumentEvent e){napBang();} });
        return p;
    }
    private JScrollPane taoBang(){
        model=new DefaultTableModel(new Object[]{ "ID", "Ma", "Ho va ten", "SDT", "Email", "Dia chi", "Ngay sinh (yyyy-MM-dd)" },0){ public boolean isCellEditable(int r,int c){return false;} };
        table=new JTable(model); table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.getSelectionModel().addListSelectionListener(e->chon()); return new JScrollPane(table);
    }
    private void chon(){ int i=table.getSelectedRow(); if(i<0) return; int idx=1; txt_ma.setText(String.valueOf(model.getValueAt(i,idx++))); txt_hovaten.setText(String.valueOf(model.getValueAt(i,idx++))); txt_sdt.setText(String.valueOf(model.getValueAt(i,idx++))); txt_email.setText(String.valueOf(model.getValueAt(i,idx++))); txt_diachi.setText(String.valueOf(model.getValueAt(i,idx++))); txt_ngaysinh.setText(model.getValueAt(i,idx++)==null? "": model.getValueAt(i,idx-1).toString()); }
    private void xuatCSV(){ try{ javax.swing.JFileChooser ch=new javax.swing.JFileChooser(); ch.setSelectedFile(new java.io.File("export.csv")); if(ch.showSaveDialog(this)==javax.swing.JFileChooser.APPROVE_OPTION){ XuatCSV.xuatBang(table, ch.getSelectedFile()); JOptionPane.showMessageDialog(this, "Da xuat: "+ch.getSelectedFile().getAbsolutePath()); } }catch(Exception ex){ JOptionPane.showMessageDialog(this,"Loi xuat: "+ex.getMessage()); } }
    private boolean phuHopTuKhoa(String s, String q){ if(q==null||q.isEmpty()) return true; if(s==null) return false; return s.toLowerCase().contains(q.toLowerCase()); }
    private boolean kiemTraBoLoc(HocVien o){ String q=txtTimKiem==null?"":txtTimKiem.getText().trim(); return ((phuHopTuKhoa(o.getMa(), q) || phuHopTuKhoa(o.getHovaten(), q) || phuHopTuKhoa(o.getSdt(), q) || phuHopTuKhoa(o.getEmail(), q) || phuHopTuKhoa(o.getDiachi(), q)) && (( (txtTuNgaySinh==null||txtTuNgaySinh.getText().isEmpty()|| (o.getNgaysinh()!=null && !o.getNgaysinh().isBefore(java.time.LocalDate.parse(txtTuNgaySinh.getText().trim())))) && (txtDenNgaySinh==null||txtDenNgaySinh.getText().isEmpty()|| (o.getNgaysinh()!=null && !o.getNgaysinh().isAfter(java.time.LocalDate.parse(txtDenNgaySinh.getText().trim())))) ))); }
    private void napBang(){ model.setRowCount(0); java.util.List<HocVien> list=service.timTatCa(); for(HocVien o: list){ if(kiemTraBoLoc(o)) model.addRow(new Object[]{ o.getId(), o.getMa(), o.getHovaten(), o.getSdt(), o.getEmail(), o.getDiachi(), o.getNgaysinh() }); } }
    private void them(){ try{ HocVien o=new HocVien(); o.setMa(txt_ma.getText().trim()); o.setHovaten(txt_hovaten.getText().trim()); o.setSdt(txt_sdt.getText().trim()); o.setEmail(txt_email.getText().trim()); o.setDiachi(txt_diachi.getText().trim()); if(!txt_ngaysinh.getText().trim().isEmpty()) o.setNgaysinh(java.time.LocalDate.parse(txt_ngaysinh.getText().trim())); service.tao(o); }catch(Exception ex){ JOptionPane.showMessageDialog(this, "Loi them: "+ex.getMessage()); } }
    private void sua(){ int i=table.getSelectedRow(); if(i<0){JOptionPane.showMessageDialog(this,"Chon dong de sua");return;} try{ HocVien o=new HocVien(); o.setId((Integer)model.getValueAt(i,0)); o.setMa(txt_ma.getText().trim()); o.setHovaten(txt_hovaten.getText().trim()); o.setSdt(txt_sdt.getText().trim()); o.setEmail(txt_email.getText().trim()); o.setDiachi(txt_diachi.getText().trim()); if(!txt_ngaysinh.getText().trim().isEmpty()) o.setNgaysinh(java.time.LocalDate.parse(txt_ngaysinh.getText().trim())); service.capNhat(o); }catch(Exception ex){ JOptionPane.showMessageDialog(this,"Loi sua: "+ex.getMessage()); } }
    private void xoa(){ int i=table.getSelectedRow(); if(i<0){JOptionPane.showMessageDialog(this,"Chon dong de xoa");return;} if(JOptionPane.showConfirmDialog(this,"Xoa?","Xac nhan",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){ try{ service.xoa((Integer)model.getValueAt(i,0)); }catch(Exception ex){ JOptionPane.showMessageDialog(this,"Loi xoa: "+ex.getMessage()); } } }
}

