DROP DATABASE IF EXISTS trungtam;
CREATE DATABASE trungtam CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE trungtam;
CREATE TABLE vaitro (id INT AUTO_INCREMENT PRIMARY KEY, ten VARCHAR(50) UNIQUE NOT NULL);
CREATE TABLE taikhoan (id INT AUTO_INCREMENT PRIMARY KEY, tendangnhap VARCHAR(100) UNIQUE NOT NULL, matkhau_hash VARCHAR(255) NOT NULL, hovaten VARCHAR(150) NOT NULL, vaitro_id INT NOT NULL, FOREIGN KEY (vaitro_id) REFERENCES vaitro(id));
CREATE TABLE hocvien (id INT AUTO_INCREMENT PRIMARY KEY, ma VARCHAR(20) UNIQUE NOT NULL, hovaten VARCHAR(150) NOT NULL, sdt VARCHAR(20), email VARCHAR(150), diachi VARCHAR(255), ngaysinh DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE giaovien (id INT AUTO_INCREMENT PRIMARY KEY, hovaten VARCHAR(150) NOT NULL, sdt VARCHAR(20), email VARCHAR(150), chunghiem VARCHAR(150));
CREATE TABLE monhoc (id INT AUTO_INCREMENT PRIMARY KEY, ma VARCHAR(20) UNIQUE NOT NULL, ten VARCHAR(200) NOT NULL, hocphi DECIMAL(12,2) NOT NULL, sotuantu DECIMAL(5,2) NOT NULL);
CREATE TABLE lophoc (id INT AUTO_INCREMENT PRIMARY KEY, monhoc_id INT NOT NULL, giaovien_id INT NOT NULL, phong VARCHAR(50), lich VARCHAR(100), ngaybatdau DATE, ngayketthuc DATE, FOREIGN KEY (monhoc_id) REFERENCES monhoc(id), FOREIGN KEY (giaovien_id) REFERENCES giaovien(id));
CREATE TABLE dangky (id INT AUTO_INCREMENT PRIMARY KEY, hocvien_id INT NOT NULL, lophoc_id INT NOT NULL, ngaydangky TIMESTAMP DEFAULT CURRENT_TIMESTAMP, trangthai VARCHAR(20) DEFAULT 'DANG_HOC', UNIQUE KEY uq_hv_lh (hocvien_id, lophoc_id), FOREIGN KEY (hocvien_id) REFERENCES hocvien(id), FOREIGN KEY (lophoc_id) REFERENCES lophoc(id));
CREATE TABLE thanhtoan (id INT AUTO_INCREMENT PRIMARY KEY, dangky_id INT NOT NULL, sotien DECIMAL(12,2) NOT NULL, ngaytt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, phuongthuc VARCHAR(20) DEFAULT 'TIENMAT', ghichu VARCHAR(255), FOREIGN KEY (dangky_id) REFERENCES dangky(id));
INSERT INTO vaitro(ten) VALUES ('ADMIN'), ('NHANVIEN');
INSERT INTO taikhoan(tendangnhap, matkhau_hash, hovaten, vaitro_id) VALUES ('admin', SHA2('admin',256), 'Quan tri he thong', 1), ('staff', SHA2('staff',256), 'Nhan vien', 2);
INSERT INTO hocvien(ma, hovaten, sdt, email, diachi, ngaysinh) VALUES ('HV001','Nguyen Van A','0901234567','a@example.com','Q1, HCM','2005-05-10'),('HV002','Tran Thi B','0909999999','b@example.com','Q7, HCM','2006-09-21');
INSERT INTO giaovien(hovaten,sdt,email,chunghiem) VALUES ('Thay Pham Cong','0911111111','pc@example.com','Toan'),('Co Le Hanh','0922222222','lh@example.com','Tieng Anh');
INSERT INTO monhoc(ma,ten,hocphi,sotuantu) VALUES ('TOAN10','Toan 10 - Nang cao',1500000,8),('IELTSF','IELTS Foundation',2500000,10);
INSERT INTO lophoc(monhoc_id,giaovien_id,phong,lich,ngaybatdau,ngayketthuc) VALUES (1,1,'P101','Thu 2-4 18:00-20:00','2025-09-15','2025-11-10'),(2,2,'P202','Thu 3-5 18:30-20:30','2025-09-20','2025-11-28');