db.vendor=mysql
db.driver=com.mysql.cj.jdbc.Driver
db.mysql.driver=com.mysql.cj.jdbc.Driver
db.mssql.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.mysql.url=jdbc:mysql://localhost:3306/trungtam?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.mysql.user=root
db.mysql.password=6820
